import { Injectable } from '@angular/core';
import { Menu } from './menu';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class MenuService {
  baseUrl = 'https://crudcrud.com/api/e8733c3b5f734f68a0618cb2e93b6e72'; // berbeda untuk setiap mahasiswa

  constructor(private http: HttpClient) {}

  getMenus() {
    return this.http.get(`${this.baseUrl}/food`);
  }

  getMenu(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/food/${id}`);
  }

  postMenu(menu: Menu) {
    delete menu._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/food`, menu);
  }

  updateMenu(menu: Menu) {
    const id = menu._id; // we copy the original id
    delete menu._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/food/${id}`, menu);
  }

  deleteMenu(hero: Menu) {
    const id = hero._id; // we copy the original id
    return this.http.delete(`${this.baseUrl}/food/${id}`);
  }
}
